### ISSUE TITLE
update state immediately in componentDidMount will not trigger componentWillReceiveProps

### ISSUE THREAD

**Issue by flyfloor** [vesparny/statty#15]
![image](https://user-images.githubusercontent.com/5626417/31531984-266bc9c4-afb0-11e7-8e24-4c902b5c1317.png)
this will not trigger component update:
![image](https://user-images.githubusercontent.com/5626417/31532002-42c9a348-afb0-11e7-8a8c-d239928525ad.png)
this will trigger:
![image](https://user-images.githubusercontent.com/5626417/31532029-6bf92310-afb0-11e7-83d3-f49f62d3be84.png)

**Comment by flyfloor** [comment]
use 'react-addons-update' for state mutation

**Comment by vesparny** [comment]
could you please provide an example on codesandbox or codepen?

**Comment by vesparny** [comment]
please have a look as this example too.

https://codesandbox.io/s/7wx3v8jqqq

I think it does something similar to what you are trying to do.

**Comment by flyfloor** [comment]
@vesparny here is a demo: https://codesandbox.io/s/j3zy0mvrp5

**Comment by vesparny** [comment]
This is interesting.

The problem is that we create subscription to state changes in `<State>` componentDidMount and it gets called after the componentDidMount method of the component returned in the render prop.

That means the broadcast subscription is not ready yet at the time you invoke the updater.

Setting up the subscription in `<State>` componentWillMount would fix the problem, but I remember @developit telling me that the right place for subscriptions is cDM.

@kentcdodds have you ever had to deal with this sort of problems?

**Comment by kentcdodds** [comment]
Yes, componentDidMount is the right place for subscriptions (one reason is that cWM will be run on the server and you don't want to subscribe to things on the server). This is an interesting problem though. I've never had to deal with it.

**Comment by vesparny** [comment]
Looping @mjackson hoping to get some help

**Comment by vesparny** [comment]
ok it's been fixed in `2.0.3`.
All I need to do was notifying subscribers (if needed) after creating subscriptions in cDM.
This ensures that children firing updates in cWM/cDM get the new state once the subscription is ready.

Thanks @jerryshew for reporting this.
